name: Website web request
on:
 # schedule:
  #  - cron: '0 * * * *'
  workflow_dispatch:
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - uses: actions/setup-python@v4
     with:
      python-version: '3.x'
   - uses: jannekem/run-python-script-action@v1
     with:
      script: |
        import requests
        import time
        url = "https://research.northumbria.ac.uk/irs/"
        response = requests.get(url, verify=False)
        print(response.status_code)
