name: Website web request
on:
  #schedule:
   # - cron: '0 * * * *'
  workflow_dispatch:
jobs:
    Start:
      runs-on: ubuntu-latest
      steps:
        - name: Website request
          uses: fjogeleit/http-request-action@master
          id: webrequest
          with:
            timeout: 100000
            url: 'https://research.northumbria.ac.uk/irs/'
            method: 'GET'
