name: Website web request
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - uses: actions/setup-python@v4
     with:
      python-version: '3.x'
      cache: 'pip'
   - run: pip install -r requirements.txt
   - run: python script.py
        
        
