name: Website web request
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
    Start:
      runs-on: ubuntu-latest
      steps:
        - name: Website request
          uses: fjogeleit/http-request-action@master
          id: webrequest
          with:
            httpsCA: ${{ secrets.certificate_irs_website }}
            timeout: 1000000
            preventFailureOnNoResponse: true
            url: 'https://research.northumbria.ac.uk/irs/'
            method: 'GET'
